<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>br.edu.ifma.labmanager</groupId>
        <artifactId>labmanager</artifactId>
        <version>0.1.0-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>identity-service</artifactId>
    <packaging>pom</packaging>
    <name>identity-service</name>
    <description>Identidade e acesso — Clean Architecture</description>

    <modules>
        <module>domain</module>
        <module>application</module>
        <module>presentation</module>
        <module>infra</module>
    </modules>
</project>
