# Profile experimental — PostgreSQL (Fase 3+)
spring.datasource.url=jdbc:postgresql://localhost:5434/scheduling
spring.datasource.username=labmanager
spring.datasource.password=labmanager
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false

logging.structured.format.console=ecs
