spring.application.name=scheduling-service-layered
server.port=8083

spring.datasource.url=jdbc:h2:mem:scheduling-layered;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.h2.console.enabled=true

labmanager.identity.base-url=http://localhost:8080
labmanager.catalog.base-url=http://localhost:8082
